In [1]:
import pandas as pd

columns_name=['beer_name', 'beer_id','brewery_name','brewery_id',
              'style','abv','date','user_name','user_id','appearance',
              'aroma','palate','taste','overall','rating','text']

df=pd.DataFrame(columns=columns_name)
with open('glutenfree_beers.txt', 'r') as file:
    for i,line in enumerate(file):
        j=i % 17
        if (j!=0):
            df.at[int(i/17),columns_name[j-1]]=line.strip().split(':',1)[1]

In [2]:
df

,beer_name,beer_id,brewery_name,brewery_id,style,abv,date,user_name,user_id,appearance,aroma,palate,taste,overall,rating,text
0,Kowloon Bay Gluten Free IPA,436710,Kowloon Bay Brewery,25260,India Pale Ale (IPA),6.6,1469527200,CacheManyHose,282160,3,7,2,6,14,3.20,Drank at Home: Eat To Live cafe. Floral hop n...
1,Glutenberg 1er Anniversaire,182791,Glutenberg Brewing Company,13241,Specialty Grain,7.5,1373796000,BiereLuc,131174,3,7,3,8,16,3.70,BiÃ¨re cuivrÃ©e. Nez houblon-caramel. En bouc...
2,Glutenberg 1er Anniversaire,182791,Glutenberg Brewing Company,13241,Specialty Grain,7.5,1368525600,lesifflebiere,237596,4,8,4,7,15,3.80,Une belle brune qui dÃ©gage immÃ©diatement de...
3,Glutenberg 1er Anniversaire,182791,Glutenberg Brewing Company,13241,Specialty Grain,7.5,1361790000,Viper666,22083,3,7,3,7,13,3.30,Bouteille 750ml. De couleur ambrÃ©e foncÃ©e e...
4,Glutenberg 1er Anniversaire,182791,Glutenberg Brewing Company,13241,Specialty Grain,7.5,1360580400,czar,104498,3,6,3,6,14,3.20,pours clear medium dark golden with a decent ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3765,Grain dOrge Glutenfri Ekologisk Lager,477827,Grain dOrge (Brasseurs De Gayant),759,Pale Lager,3.5,1492164000,gnoff,32615,2,6,2,6,11,2.70,"25 cl bottle from Copp Avenyn, GÃ¶teborg. Sam..."
3766,Grain dOrge Glutenfri Ekologisk Lager,477827,Grain dOrge (Brasseurs De Gayant),759,Pale Lager,3.5,1489489200,Turtles,333213,2,4,2,4,9,2.10,"250ml bottle. Clear pale golden, medium size ..."
3767,Grain dOrge Glutenfri Ekologisk Lager,477827,Grain dOrge (Brasseurs De Gayant),759,Pale Lager,3.5,1487502000,SamTheBarrel,269531,3,6,3,6,8,2.60,250ml green bottle poured into a lager glass....
3768,Grain dOrge Glutenfri Ekologisk Lager,477827,Grain dOrge (Brasseurs De Gayant),759,Pale Lager,3.5,1483786800,Malin_aiisa,361626,2,6,3,5,11,2.70,"Bottle. Pours clear amber, no head. Aroma mal..."
3769,Grain dOrge Glutenfri Ekologisk Lager,477827,Grain dOrge (Brasseurs De Gayant),759,Pale Lager,3.5,1483786800,finol,80747,2,4,2,4,7,1.90,"Bottle, wedding gift from vjohans.Pours amber..."

In [3]:
df['text']

0        Drank at Home: Eat To Live cafe. Floral hop n...
1        BiÃ¨re cuivrÃ©e. Nez houblon-caramel. En bouc...
2        Une belle brune qui dÃ©gage immÃ©diatement de...
3        Bouteille 750ml. De couleur ambrÃ©e foncÃ©e e...
4        pours clear medium dark golden with a decent ...
                              ...
3765     25 cl bottle from Copp Avenyn, GÃ¶teborg. Sam...
3766     250ml bottle. Clear pale golden, medium size ...
3767     250ml green bottle poured into a lager glass....
3768     Bottle. Pours clear amber, no head. Aroma mal...
3769     Bottle, wedding gift from vjohans.Pours amber...
Name: text, Length: 3770, dtype: object

In [7]:
import datetime
dates=[ int(date) for date in df['date']]
readable_date = [datetime.datetime.fromtimestamp(timestamp) for timestamp in dates]
df['year']=[ time.year for time in readable_date]
df['month']=[ time.month for time in readable_date]
df['year']

0       2016
1       2013
2       2013
3       2013
4       2013
        ...
3765    2017
3766    2017
3767    2017
3768    2017
3769    2017
Name: year, Length: 3770, dtype: int64

In [8]:
csv_file_path = 'glutenfree.csv'  
df.to_csv(csv_file_path, index=False)

In [9]:
columns_name = ['beer_name', 'beer_id', 'brewery_name', 'brewery_id',
                'style', 'abv', 'date', 'user_name', 'user_id', 'appearance',
                'aroma', 'palate', 'taste', 'overall', 'rating', 'text']

# Create an empty DataFrame with the specified column names
df = pd.DataFrame(columns=columns_name)

with open('micro_breweries.txt', 'r') as file:
    data = {}
    for i, line in enumerate(file):
        if i % 17 == 0:
            # This is the last line of a group, so add the data to the DataFrame
            #df = pd.concat([df, pd.DataFrame(data)], ignore_index=True)
            df = df._append(data, ignore_index=True)
            data = {}
        else:
            #print(line)
            # Split the line at the first ':' and assign the values to the corresponding column
            key, value = line.strip().split(':', 1)
            data[columns_name[i % 17 - 1]] = value

In [10]:
df

,beer_name,beer_id,brewery_name,brewery_id,style,abv,date,user_name,user_id,appearance,aroma,palate,taste,overall,rating,text
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AdstraGold 188 Nutty IPA,224983,AdstraGold Microbrewery & Bistro Bar,15008,India Pale Ale (IPA),3.0,1476698400,kermis,111648,3,5,2,5,10,2.50,"Draft at AdstraGold, Singapore. Dark brown wi..."
2,AdstraGold 188 Nutty IPA,224983,AdstraGold Microbrewery & Bistro Bar,15008,India Pale Ale (IPA),3.0,1476698400,jmgreenuk,111989,3,5,2,5,10,2.50,Tap at the Brewpub. Poured a clear dark brown...
3,AdstraGold 188 Nutty IPA,224983,AdstraGold Microbrewery & Bistro Bar,15008,India Pale Ale (IPA),3.0,1395572400,Chux,308206,1,1,1,1,1,0.50,You have got to be joking. This is no IPA and...
4,AdstraGold 188 Nutty IPA,224983,AdstraGold Microbrewery & Bistro Bar,15008,India Pale Ale (IPA),3.0,1387796400,fiulijn,1786,4,6,1,5,11,2.70,Draught at the brewpubCloudy brown color with...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32539,Chiangmai Weizen Bock,45850,Chiangmai German Microbrewery,4253,Weizen Bock,7.5,1325242800,deanso,21776,4,6,4,6,13,3.30,50cl on tap at the brewery.Good white head. ...
32540,Chiangmai Weizen Bock,45850,Chiangmai German Microbrewery,4253,Weizen Bock,7.5,1113127200,TimE,4953,4,8,4,8,16,4.00,The star of the show. Deep amber brownish co...
32541,Brew Pavilion Lager,16784,Brew Pavilion Microbrewery Pub & Restaurant,2865,Pale Lager,5.0,1072090800,omhper,2778,4,5,3,6,10,2.80,Sampled draught at the brewpub.Quite funny sp...
32542,Brew Pavilion Lager,16784,Brew Pavilion Microbrewery Pub & Restaurant,2865,Pale Lager,5.0,1033812000,jazz88,3847,3,6,3,7,15,3.40,Tap. Golden yellow with a foamy white head w...
32543,Brew Pavilion Wiezen,16783,Brew Pavilion Microbrewery Pub & Restaurant,2865,German Hefeweizen,5.5,1072090800,omhper,2778,4,7,3,6,11,3.10,Sampled draught at the brewpub.Huge place! Wh...

In [26]:
df['date']

0                NaN
1         1476698400
2         1476698400
3         1395572400
4         1387796400
            ...
32539     1325242800
32540     1113127200
32541     1072090800
32542     1033812000
32543     1072090800
Name: date, Length: 32544, dtype: object

In [40]:
(pd.isna('NaN'))

False

In [43]:
dates=[int(date) if not pd.isna(date) else None for date in df['date']]
readable_dates = []
for timestamp in dates:

    if pd.isna(timestamp):
        readable_dates.append(None)
    else:
        readable_dates.append(datetime.datetime.fromtimestamp(timestamp))

df['year'] = [time.year if not pd.isna(time) else 'NaN' for time in readable_dates]
df['month'] = [time.month if not pd.isna(time) else 'NaN' for time in readable_dates]

In [44]:
csv_file_path = 'micro-breweries.csv'  
df.to_csv(csv_file_path, index=False)