In [1]:
with open("ratings.txt") as f:
    for i in range(100):
        print(next(f))

beer_name: 33 Export (Gabon)

beer_id: 410549

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.0

date: 1461664800

user_name: Manslow

user_id: 175852

appearance: 2

aroma: 4

palate: 2

taste: 4

overall: 8

rating: 2.00

text: Puszka 0,33l dzięki Christoph . Kolor jasnozłoty, piana biała drobnoziarnista szybko opada. Aromat słodowy, lekko słodkie.Dość dobre.



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1487329200

user_name: MAGICuenca91

user_id: 442761

appearance: 2

aroma: 3

palate: 2

taste: 4

overall: 8

rating: 1.90

text: Cerveza pale lager gabonesa. MÃ¡s floja que la Regab.Aroma escaso, apariencia pÃ¡lida, muy poco cuerpo y poco regusto en el paladar.Si algÃºn dÃ­a fuera a GabÃ³n pedirÃ­a una mÃ¡s para volver a probarla y el resto del tiempo pedirÃ­a la Regab sin duda, que tampoco es que sea nada del otro mundo, pero es superior a Ã©sta.



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1466762400

user_name: Sibarh

user_id: 288889

appearance: 3

aroma: 3

palate: 2

taste: 3

overall: 5

rating: 1.60

text: Kolor- złoty, klarowny. Piana - drobna, średnio wysoka, nie trwała. Zapach - lekki słodowy. Smak - lekki słÃ³d i chmiel, lekki kwasek, lekka słodycz i goryczka



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1451646000

user_name: fombe89

user_id: 250510

appearance: 4

aroma: 3

palate: 1

taste: 2

overall: 5

rating: 1.50

text: Botella, de GabÃ³n regalo familiar.31/01/2015Color amarillo, aromas y sabores a maiz, cuerpo medio



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1445594400

user_name: kevnic2008

user_id: 122778

appearance: 2

aroma: 4

palate: 2

taste: 4

overall: 7

rating: 1.90

text: Many thanks for this beer to Erzengel. Pours light golden with medium head. Light bodied crisp taste with low carbonation. Sweet finish.



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1444644000

user_name: Beerhunter111

user_id: 227834

appearance: 2

aroma: 3

palate: 2

taste: 3

overall: 9

rating: 1.90

In [2]:
f.close()

In [3]:
with open("reviews.txt") as t:
    for i in range(100):
        print(next(t))

beer_name: 33 Export (Gabon)

beer_id: 410549

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.0

date: 1461664800

user_name: Manslow

user_id: 175852

appearance: 2

aroma: 4

palate: 2

taste: 4

overall: 8

rating: 2.00

text: Puszka 0,33l dzięki Christoph . Kolor jasnozłoty, piana biała drobnoziarnista szybko opada. Aromat słodowy, lekko słodkie.Dość dobre.



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1487329200

user_name: MAGICuenca91

user_id: 442761

appearance: 2

aroma: 3

palate: 2

taste: 4

overall: 8

rating: 1.90

text: Cerveza pale lager gabonesa. MÃ¡s floja que la Regab.Aroma escaso, apariencia pÃ¡lida, muy poco cuerpo y poco regusto en el paladar.Si algÃºn dÃ­a fuera a GabÃ³n pedirÃ­a una mÃ¡s para volver a probarla y el resto del tiempo pedirÃ­a la Regab sin duda, que tampoco es que sea nada del otro mundo, pero es superior a Ã©sta.



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1466762400

user_name: Sibarh

user_id: 288889

appearance: 3

aroma: 3

palate: 2

taste: 3

overall: 5

rating: 1.60

text: Kolor- złoty, klarowny. Piana - drobna, średnio wysoka, nie trwała. Zapach - lekki słodowy. Smak - lekki słÃ³d i chmiel, lekki kwasek, lekka słodycz i goryczka



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1451646000

user_name: fombe89

user_id: 250510

appearance: 4

aroma: 3

palate: 1

taste: 2

overall: 5

rating: 1.50

text: Botella, de GabÃ³n regalo familiar.31/01/2015Color amarillo, aromas y sabores a maiz, cuerpo medio



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1445594400

user_name: kevnic2008

user_id: 122778

appearance: 2

aroma: 4

palate: 2

taste: 4

overall: 7

rating: 1.90

text: Many thanks for this beer to Erzengel. Pours light golden with medium head. Light bodied crisp taste with low carbonation. Sweet finish.



beer_name: Castel Beer (Gabon)

beer_id: 105273

brewery_name: Sobraga

brewery_id: 3198

style: Pale Lager

abv: 5.2

date: 1444644000

user_name: Beerhunter111

user_id: 227834

appearance: 2

aroma: 3

palate: 2

taste: 3

overall: 9

rating: 1.90

In [1]:
import pandas as pd
breweries = pd.read_csv('breweries.csv')
beers=pd.read_csv('beers.csv')

In [2]:
microbreweries = breweries[breweries['name'].str.contains('micro', case=False, na=False)]
microbreweries

,id,location,name,nbr_beers
35,15008,Singapore,AdstraGold Microbrewery & Bistro Bar,16
54,21778,Singapore,The 1925 Microbrewery & Restaurant,7
703,23243,Mexico,Microcerveceria Artesanal Santa Cruz,1
704,11664,Mexico,Microcerveceria La Legendaria,5
993,5562,Canada,Paddock Wood Microbrewery,76
...,...,...,...,...
23668,19998,France,Microbrasserie Grenaille,8
23669,23675,France,Microbrasserie Lou Soulèu,3
23670,29249,France,Microbrasserie RZN -City Ales-,4
24099,4253,Thailand,Chiangmai German Microbrewery,8
24171,2865,Thailand,Brew Pavilion Microbrewery Pub & Restaurant,2

In [3]:
micro_beers=beers[beers['brewery_name'].str.contains('micro', case=False, na=False)]
micro_beers

,beer_id,beer_name,brewery_id,brewery_name,style,nbr_ratings,overall_score,style_score,avg,abv,avg_computed,zscore,nbr_matched_valid_ratings,avg_matched_valid_ratings
295,224983,AdstraGold 188 Nutty IPA,15008,AdstraGold Microbrewery & Bistro Bar,India Pale Ale (IPA),5,NaN,NaN,2.84,3.0,2.320000,NaN,0,NaN
296,226242,AdstraGold Adstrapple Cider,15008,AdstraGold Microbrewery & Bistro Bar,Cider,4,NaN,NaN,2.97,4.0,3.025000,NaN,0,NaN
297,224972,AdstraGold Dark Ale,15008,AdstraGold Microbrewery & Bistro Bar,Brown Ale,5,NaN,NaN,2.92,4.0,2.920000,NaN,0,NaN
298,224977,AdstraGold Golden Ale,15008,AdstraGold Microbrewery & Bistro Bar,Golden Ale/Blond Ale,6,NaN,NaN,2.76,3.0,2.666667,NaN,0,NaN
299,457539,AdstraGold Golden Oak Ale,15008,AdstraGold Microbrewery & Bistro Bar,Golden Ale/Blond Ale,3,NaN,NaN,3.07,3.5,3.266667,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441668,58193,Chiangmai Songkran,4253,Chiangmai German Microbrewery,Heller Bock,2,NaN,NaN,2.80,7.6,2.850000,NaN,0,NaN
441669,29582,Chiangmai Weizen,4253,Chiangmai German Microbrewery,German Hefeweizen,5,NaN,NaN,2.95,5.3,3.200000,NaN,0,NaN
441670,45850,Chiangmai Weizen Bock,4253,Chiangmai German Microbrewery,Weizen Bock,3,NaN,NaN,3.01,7.5,3.533333,NaN,0,NaN
442018,16784,Brew Pavilion Lager,2865,Brew Pavilion Microbrewery Pub & Restaurant,Pale Lager,2,NaN,NaN,2.94,5.0,3.100000,NaN,0,NaN
442019,16783,Brew Pavilion Wiezen,2865,Brew Pavilion Microbrewery Pub & Restaurant,German Hefeweizen,2,NaN,NaN,3.11,5.5,3.400000,NaN,0,NaN

In [4]:
micro_beers['overall_score'].isna().sum()

2903

In [5]:
glutenfree=beers[beers['beer_name'].str.contains('gluten', case=False, na=False)]
glutenfree

,beer_id,beer_name,brewery_id,brewery_name,style,nbr_ratings,overall_score,style_score,avg,abv,avg_computed,zscore,nbr_matched_valid_ratings,avg_matched_valid_ratings
2416,436710,Kowloon Bay Gluten Free IPA,25260,Kowloon Bay Brewery,India Pale Ale (IPA),1,NaN,NaN,2.98,6.6,3.200000,NaN,0,NaN
9804,182791,Glutenberg 1er Anniversaire,13241,Glutenberg Brewing Company,Specialty Grain,19,74.0,80.0,3.26,7.5,3.421053,NaN,0,NaN
9805,454028,Glutenberg 5e Anniversaire,13241,Glutenberg Brewing Company,India Pale Ale (IPA),1,NaN,NaN,3.11,6.0,3.800000,NaN,0,NaN
9806,162109,Glutenberg 8,13241,Glutenberg Brewing Company,Specialty Grain,17,40.0,38.0,2.97,5.0,3.052941,NaN,0,NaN
9807,340007,Glutenberg APA Safran Pamplemousse,13241,Glutenberg Brewing Company,Specialty Grain,1,NaN,NaN,2.96,5.5,3.100000,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434130,533787,Vézelay Lager Blonde Bio Sans Gluten,15026,Brasserie de Vézelay,Specialty Grain,1,NaN,NaN,2.94,4.0,3.000000,NaN,0,NaN
434476,328974,Grain dOrge Sans Gluten Bio (Gluten Free / Gl...,29110,Brasserie Goudale (Saint-Omer),Golden Ale/Blond Ale,44,8.0,4.0,2.39,5.5,2.340909,NaN,0,NaN
435150,381938,Castelain Jade Sans Gluten,739,Castelain,Pale Lager,11,9.0,86.0,2.44,4.5,2.281818,-2.315954,11,2.281818
438865,475575,Grain dOrge Glutenfri Ekologisk Ale,759,Grain dOrge (Brasseurs De Gayant),Golden Ale/Blond Ale,15,10.0,7.0,2.50,3.5,2.400000,NaN,0,NaN
438866,477827,Grain dOrge Glutenfri Ekologisk Lager,759,Grain dOrge (Brasseurs De Gayant),Pale Lager,5,NaN,NaN,2.62,3.5,2.400000,NaN,0,NaN

In [6]:
glutenfree['overall_score'].isna().sum()

166

In [11]:
with open('ratings.txt', 'r') as file:
    beer_id=[line.strip() for i,line in enumerate(file) if i % 17 ==1]

In [12]:
beer_id[1:20]

['beer_id: 105273',
 'beer_id: 105273',
 'beer_id: 105273',
 'beer_id: 105273',
 'beer_id: 105273',
 'beer_id: 105273',
 'beer_id: 105273',
 'beer_id: 105273',
 'beer_id: 105273',
 'beer_id: 105273',
 'beer_id: 19445',
 'beer_id: 19445',
 'beer_id: 19445',
 'beer_id: 19445',
 'beer_id: 19445',
 'beer_id: 19445',
 'beer_id: 19445',
 'beer_id: 19445',
 'beer_id: 19445']

In [13]:
beers_id=[id.split(' ',2)[1] for id in beer_id]

In [14]:
beers_id[1:20]

['105273',
 '105273',
 '105273',
 '105273',
 '105273',
 '105273',
 '105273',
 '105273',
 '105273',
 '105273',
 '19445',
 '19445',
 '19445',
 '19445',
 '19445',
 '19445',
 '19445',
 '19445',
 '19445']

In [15]:
beers_id=[int(id) for id in beers_id]

In [15]:
beers_id[1:20]

[105273,
 105273,
 105273,
 105273,
 105273,
 105273,
 105273,
 105273,
 105273,
 105273,
 19445,
 19445,
 19445,
 19445,
 19445,
 19445,
 19445,
 19445,
 19445]

In [20]:
(micro_beers['beer_id'])[1:20]

296    226242
297    224972
298    224977
299    457539
300    182177
301    224976
302    457551
303    457548
304    224981
305    224969
306    457531
307    457549
308    224979
309    224974
310    457532
517    308489
518    529494
519    529498
520    308488
Name: beer_id, dtype: int64

In [28]:
print(224972 in (micro_beers['beer_id'])[1:20].to_numpy())

True

In [30]:
import numpy as np

positions = np.where(np.isin(beers_id, micro_beers['beer_id'].to_numpy()))[0]
positions

array([   3334,    3335,    3336, ..., 7121315, 7121316, 7121317])

In [31]:
beers_id[3334]

224983

In [32]:
micro_beers[micro_beers['beer_id']==224983]

,beer_id,beer_name,brewery_id,brewery_name,style,nbr_ratings,overall_score,style_score,avg,abv,avg_computed,zscore,nbr_matched_valid_ratings,avg_matched_valid_ratings
295,224983,AdstraGold 188 Nutty IPA,15008,AdstraGold Microbrewery & Bistro Bar,India Pale Ale (IPA),5,NaN,NaN,2.84,3.0,2.32,NaN,0,NaN

In [33]:
len(positions)

32544

In [34]:
micro_beers['nbr_ratings'].sum()

32544

In [48]:
lines_to_keep=[]
for i in range(0,17):
    new=[position*17+i for position in positions]
    lines_to_keep=lines_to_keep+new
lines_to_keep.sort()
lines_to_keep[1:20]

[56679,
 56680,
 56681,
 56682,
 56683,
 56684,
 56685,
 56686,
 56687,
 56688,
 56689,
 56690,
 56691,
 56692,
 56693,
 56694,
 56695,
 56696,
 56697]

In [49]:
input_file_path = 'ratings.txt'
output_file_path = 'micro_breweries.txt'

import linecache
with  open(output_file_path, 'w') as output_file:
    for line_number in lines_to_keep:
        line = linecache.getline(input_file_path, line_number)
        output_file.write(line)
# Close the output file
output_file.close()

In [53]:

positions_gluten = np.where(np.isin(beers_id, glutenfree['beer_id'].to_numpy()))[0]
positions_gluten

array([  22376,  143576,  143577, ..., 7069755, 7069756, 7069757])

In [54]:
beers_id[22376]

436710

In [55]:
glutenfree[glutenfree['beer_id']==436710]

,beer_id,beer_name,brewery_id,brewery_name,style,nbr_ratings,overall_score,style_score,avg,abv,avg_computed,zscore,nbr_matched_valid_ratings,avg_matched_valid_ratings
2416,436710,Kowloon Bay Gluten Free IPA,25260,Kowloon Bay Brewery,India Pale Ale (IPA),1,NaN,NaN,2.98,6.6,3.2,NaN,0,NaN

In [57]:
len(positions_gluten)

3770

In [58]:
glutenfree['nbr_ratings'].sum()

3770

In [60]:
lines_keep=[]
for i in range(0,17):
    new=[position*17+i for position in positions_gluten]
    lines_keep=lines_keep+new
lines_keep.sort()
lines_keep[1:20]

[380393,
 380394,
 380395,
 380396,
 380397,
 380398,
 380399,
 380400,
 380401,
 380402,
 380403,
 380404,
 380405,
 380406,
 380407,
 380408,
 2440792,
 2440793,
 2440794]

In [61]:
input_file_path = 'ratings.txt'
output_file_path = 'glutenfree_beers.txt'

import linecache
with  open(output_file_path, 'w') as output_file:
    for line_number in lines_keep:
        line = linecache.getline(input_file_path, line_number)
        output_file.write(line)
# Close the output file
output_file.close()